FROM        openjdk:8-jdk as build
WORKDIR     /depot
COPY        . .
RUN         ./gradlew -Penv=prod :log-processor:installDist

FROM        openjdk:jre-alpine
MAINTAINER  neo
EXPOSE      8080
WORKDIR     /opt
COPY        --from=build /depot/build/log-processor/install/log-processor /opt/log-processor
ENTRYPOINT  ["/bin/sh", "-c", "/opt/log-processor/bin/log-processor"]
